### ISSUE TITLE
Broken search functionality

### ISSUE THREAD

**Issue by mitchuman** [storyblok/storyblok-design-system#372]
[storyblokurl]: https://www.storyblok.com?utm_source=github.com&utm_medium=issue-template

Not sure if this repo is the best place to report the bug but...

The search functionality in the CMS does not function properly—i.e. it seems it can only show results for the first entered word only.

---

## Expected Behavior

Enter `modular blog` and show results for the first item show in the list *Modular Blog List*. Case insensitive search preferred.
(Refer to screenshot)

<img width="646" alt="Screen Shot 2023-02-28 at 11 05 07 AM" src="https://user-images.githubusercontent.com/73133191/221955106-d2e247ab-d5d7-4cb7-a9f4-d9cefef6232c.png">

<img width="652" alt="Screen Shot 2023-02-28 at 11 11 15 AM" src="https://user-images.githubusercontent.com/73133191/221955232-9fde2e0c-bd31-437b-a47b-bea2bff0cbc2.png">

## Current Behavior

Entering `modular` shows a accurate results. But as soon as I type the next word, it yields zero results.
Tried with different casing (`Modular Blog`) and exact match (`Modular Blog List`) but same results.

## Steps to Reproduce

1. Navigate to a page and create schema to allow for block searching
2. Invoke the search menu and start typing.
3. View results.

**Comment by lisilinhart** [comment]
Hi @mitchuman, I will forward this to the team but the correct place to report is through the customer support or the jira service desk https://storyblok.atlassian.net/servicedesk
