### ISSUE TITLE
Seems like 3.8.0 npm package is missing dist

### ISSUE THREAD

**Issue by alvarosabu** [storyblok/storyblok-design-system#391]
[storyblokurl]: https://www.storyblok.com?utm_source=github.com&utm_medium=issue-template

I updated to latest `v3.8.0` but seems like the npm package only contains the `src` and not the dist folder for the exports declared on the package.json 

![Screenshot 2023-04-24 at 10 31 35](https://user-images.githubusercontent.com/4699008/233944923-6f241b3e-887c-4b13-b547-ff373bab65cd.png)

---

## Expected Behavior

main/module/exports are available on the package

## Current Behavior

Failed to resolve entry for package "@storyblok/design-system". The package may have incorrect main/module/exports specified in its package.json

## Steps to Reproduce

1. Go to https://stackblitz.com/edit/vitejs-vite-fz4dii?file=src%2Fmain.ts&terminal=dev
2. Run `npm run dev`

**Comment by lisilinhart** [comment]
Solved in 3.9.0
