### ISSUE TITLE
SbPagination - wrong event name for next/prev page change in documentation example

### ISSUE THREAD

**Issue by kesonno** [storyblok/storyblok-design-system#452]
Hi,

in the [Storybook page for SbPagination component](https://blok.ink/?path=/docs/navigation-sbpagination--documentation), the code shown for the examples has a wrong name for both events of page change with prev/next links. In the example there are:
* v-on:previous-page
* v-on:next-page

while the right event names are:
* v-on:on-previous-page
* v-on:on-next-page

**Comment by lorenaramonda** [comment]
Thank you @kesonno , we will proceed by removing the redundant `on` prefix so that the event names listeners will be:

```
v-on:previous-page
v-on:next-page
```
as currently shown in the doc.

Thanks for pointing this out! 🙌

**Comment by lisilinhart** [comment]
@lorenaramonda can we close out this issue?

**Comment by lorenaramonda** [comment]
sure we can!
