### ISSUE TITLE
Missing required prop: "tagsCountTooltip"

### ISSUE THREAD

**Issue by stijns96** [storyblok/storyblok-design-system#478]
The `tags-count-tooltip` props on the `SelectInnerTag` component is required, but it looks like it's not provided to the component.

![image](https://github.com/storyblok/storyblok-design-system/assets/47820758/326a88b0-7f43-40c4-8114-a3aa35571956)

![image](https://github.com/storyblok/storyblok-design-system/assets/47820758/8ebfbd97-fe88-421d-ae92-3336791bdee2)

**Comment by lisilinhart** [comment]
I think this is solved already
